from .logup import LogupSerializer
from .contact_networks import ContactNetworksSerializer
from .user_tags import UserTagsSerializer
from .user_profile_picture import UserProfilePictureSerializer
from .clients_opinions import ClientsOpinionsSerializer
from .login import LoginSerializer
from .product import NewProductSerializer
from .followers import FollowersSerializer
from .favorites_products import FavoritesProductsSerializer