# Generated by Django 3.1.4 on 2021-01-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=65)),
                ('picture', models.CharField(blank=True, max_length=256, null=True)),
                ('username', models.CharField(error_messages={'unique': 'Este nombre de usuario ya fue tomado.'}, max_length=25, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(error_messages={'unique': 'Otro usuario usa este correo.'}, max_length=125, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactNetworksModel',
            fields=[
                ('user', models.OneToOneField(error_messages={'unique': 'Este usuario ya añadió sus redes de contacto.'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='root.usermodel')),
                ('instagram', models.CharField(blank=True, error_messages={'unique': 'Otro usuario ya registró esta cuenta.'}, max_length=30, null=True, unique=True)),
                ('facebook', models.CharField(blank=True, error_messages={'unique': 'Otro usuario ya registró esta cuenta.'}, max_length=50, null=True, unique=True)),
                ('whatsapp', models.CharField(blank=True, error_messages={'unique': 'Otro usuario ya registró esta cuenta.'}, max_length=15, null=True, unique=True)),
                ('twitter', models.CharField(blank=True, error_messages={'unique': 'Otro usuario ya registró esta cuenta.'}, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'Otro usuario ya registró esta cuenta.'}, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTagsModel',
            fields=[
                ('user', models.OneToOneField(error_messages={'unique': 'Este usuario ya añadió sus etiquetas.'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='root.usermodel')),
                ('tags', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
