# Generated by Django 3.1.4 on 2021-02-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
