from .logup import LogupViewSet
from .contact_networks import ContactNetworksViewSet
from .user_profile_picture import UserProfilePictureViewSet
from .clients_opinions import ClientOpinionsViewSet
from .login import LoginViewSet
from .product import ProductsViewSet
from .validation import ValidationViewSet
from .followers import FollowersViewSet
from .favorites_products import FavoritesProductsViewSet
from .data_retrieve import GetDataViewSet