from .logup import LogupViewSet
from .contact_networks import ContactNetworksViewSet
from .user_profile_picture import UserProfilePictureViewSet
from .clients_opinions import ClientOpinionsViewSet
from .login import LoginViewSet
from .product import NewProductViewSet
from .get_data import GetDataViewSet
from .validation import ValidationViewSet
from .followers import FollowersViewSet
from .favorites_products import FavoritesProductsViewSet